[package]
name = "budget-model"
version = "0.0.1"
edition = "2018"
authors = ["Pete Hayes <pete@hayes.id.au>"]
license = "MPL-2.0"
description = "Realtime money manager"
readme = "README.md"

[dependencies]
chrono = "0.4"
thiserror = "1.0"
